### ISSUE TITLE
AppCompatActivity 兼容问题

### ISSUE THREAD

**Issue by s13524801** [fengjundev/Android-Skin-Loader#14]
V7 AppCompatActivity 重写兼容不

**Comment by Monster-L** [comment]
可以看看，如何处理与AppCompactActivity兼容
http://blog.csdn.net/u013085697/article/details/53898879

**Comment by zycoJamie** [comment]
将SkinInflaterFactory implements的Factory改为LayoutInflater.Factory2 可以实现兼容
