### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by lcn1988** [fengjundev/Android-Skin-Loader#2]
1.skin如何生成
2.导入项目后查不到skin字段 Unexpected namespace prefix "skin" found for tag Button

**Comment by fengjundev** [comment]
1. skin皮肤包的本质就是一个apk文件，[皮肤包实例工程](https://github.com/fengjundev/Android-Skin-Loader/tree/master/skin/BlackFantacy)，直接编译更改后缀名为.skin即可(改后缀的目的是避免用户点击安装)

2. 检查下layout文件中是否声明了命名空间
`xmlns:skin="http://schemas.android.com/android/skin"`
如果还是不行尝试下clean操作

**Comment by lcn1988** [comment]
感谢解惑，编译apk是必须签名一致吗，其次在5.1中getDrawable(int id)提示已被废弃了，希望能完善

**Comment by fengjundev** [comment]
问题已收录，谢谢反馈！
